name: Deploy to VPS

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: List dist folder
        run: |
          ls -R dist

      - name: Upload Angular build to VPS
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD_USER }}
          port: ${{ secrets.VPS_PORT }}
          source: "dist/NelisterBaseProject/browser/*"   # <-- build que está en GitHub Actions
          target: "/var/www/NelisterBaseProject/"        # <-- destino en tu VPS
      - name: Restart services
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.PASSWORD_USER }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo systemctl restart nginx